# Generated by Django 3.2.8 on 2021-12-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugid', models.IntegerField()),
                ('drugname', models.CharField(max_length=30)),
                ('isopioid', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.IntegerField()),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('credentials', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=62)),
                ('ispioidprescriber', models.CharField(max_length=5)),
                ('totalprescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=14)),
                ('stateabbrev', models.CharField(max_length=2)),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
    ]
